name: Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Test check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.0
      
      - name: Run tests and coverage
        run: |
          go test -v -coverprofile=coverage.txt -covermode=atomic ./...
